import { existsSync, readFileSync } from 'fs';
import { resolve, basename } from 'path';
import { Logger } from '../utils/logger';
import { createAIAgentsFromEnv, AIAgents } from '../../../ai';
import { GitBinding } from '@sintesi/core';
import { getSmartCheckReadmePrompt } from '../prompts/analysis';
import { ChangeAnalysisService } from './analysis-service';
import { filterGitDiff } from '../utils/diff-utils';

export interface SmartCheckResult {
    hasDrift: boolean;
    reason?: string;
    suggestion?: string;
}

export class SmartChecker {
    private logger: Logger;
    private analysisService: ChangeAnalysisService;
    private projectRoot: string;

    constructor(logger: Logger, projectRoot: string = process.cwd()) {
        this.logger = logger;
        this.analysisService = new ChangeAnalysisService(logger);
        this.projectRoot = projectRoot;
    }

    /**
     * Determine if we should analyze changes with AI based on heuristics
     * This saves tokens by avoiding AI calls for trivial changes
     */
    private shouldAnalyzeWithAI(changedFiles: string[], gitDiff: string): boolean {
        // 1. File Name Filtering
        const relevantFiles = changedFiles.filter((file) => {
            // Ignore test files
            if (
                file.match(/\.(test|spec)\.(ts|js|rs)$/) ||
                file.includes('__tests__') ||
                file.includes('tests/')
            )
                return false;
            // Ignore lockfiles and internal configs
            if (file.includes('lock.yaml') || file.includes('lock.json') || file.includes('lock'))
                return false;
            if (file.includes('.gitignore') || file.includes('.editorconfig')) return false;
            // Ignore Changelogs and Changesets (Version bumps)
            if (file.includes('CHANGELOG.md') || file.includes('.changeset/')) return false;

            // Focus on source code (TS/JS/Rust) and existing docs and configs
            return (
                file.endsWith('.ts') ||
                file.endsWith('.js') ||
                file.endsWith('.rs') ||
                file.endsWith('package.json') ||
                file.endsWith('Cargo.toml')
            );
        });

        // 2. Critical Path "Always Check"
        // If the file is in a critical directory (like commands or routes), we analyze it regardless of specific keywords.
        // NOTE: We removed package.json/Cargo.toml from here to avoid triggering on simple version bumps.
        // We rely on content heuristics (below) to catch "dependencies" or "scripts" changes.
        const isCriticalChange = relevantFiles.some(
            (file) => file.includes('/commands/') || file.includes('/routes/'),
        );

        if (isCriticalChange) {
            this.logger.debug(
                'Critical file changed (commands/routes). Skipping keyword heuristics and forcing AI check.',
            );
            return true;
        }

        // 3. Content Heuristics (Rust GitBinding)
        // We use the Rust native implementation for performance and consistency
        try {
            // Note: GitBinding.checkMeaningfulChanges is a static method in Rust (or instance method we can instantiate purely for checking)
            // If it's static in NAPI, it's GitBinding.checkMeaningfulChanges(diff)
            // But I instantiated it above in analysis service.
            // Let's create a temporary binding just to access the static method if possible, or instance.
            // Actually, in NAPI, if it's not [napi(static)], it's an instance method.
            // I defined it as `pub fn check_meaningful_changes(diff: String)` inside `impl GitBinding`.
            // Without `&self`, it IS static in Rust NAPI unless specific config.
            // Let's assume instance for safety if I'm not sure, but static is better.
            // Wait, I didn't verify index.d.ts.
            // If I look at index.d.ts generated by napi-rs for `fn foo(diff: String)` inside `impl Class`, it's usually static.

            // However, to be safe and avoid "GitService not initialized" error if I were to use instance methods:
            // "check_meaningful_changes" in Rust implementation doesn't use self.

            // Let's try static access. If TS complains or runtime fails, we fix.
            // Actually, I can just instantiate it with cwd. It's cheap?
            // "GitService::open" does open the repo.
            // But checking regex on string doesn't need repo.

            // Ideally should be static.

            // Let's use `GitBinding.checkMeaningfulChanges(gitDiff)` and see.
            // We need to import GitBinding.

            const hasMeaningful = GitBinding.checkMeaningfulChanges(gitDiff);

            if (!hasMeaningful) {
                this.logger.debug(
                    'Changes detected but no meaningful keywords found (processed by Rust). Skipping AI check.',
                );
                return false;
            }

            return true;
        } catch (e) {
            // Fallback to legacy regex if Rust binding fails (e.g. not static)
            // or just assume true to be safe.
            this.logger.warn(`Rust heuristic check failed: ${e}. Defaulting to TRUE.`);
            return true;
        }
    }

    /**
     * Checks if there are relevant code changes that might affect documentation
     * using the deterministic heuristics (no AI cost).
     */
    async hasRelevantCodeChanges(options?: { baseBranch?: string }): Promise<boolean> {
        const baseBranch = options?.baseBranch || 'origin/main';
        try {
            const context = await this.analysisService.analyze({
                baseBranch,
                projectRoot: this.projectRoot,
                fallbackToLastCommit: true,
                includeSymbols: false,
                stagedOnly: false,
            });

            if (!context.gitDiff) {
                return false;
            }

            return this.shouldAnalyzeWithAI(context.changedFiles, context.gitDiff);
        } catch (error) {
            this.logger.warn('Failed to check for relevant changes: ' + error);
            return true; // Default to true on error to be safe
        }
    }

    /**
     * Check if the README needs to be updated based on recent code changes
     */
    async checkReadme(options?: {
        baseBranch?: string;
        readmePath?: string;
    }): Promise<SmartCheckResult> {
        const readmePath = options?.readmePath || resolve(this.projectRoot, 'README.md');
        const baseBranch = options?.baseBranch || 'origin/main';

        if (!existsSync(readmePath)) {
            return { hasDrift: false }; // No README to check
        }

        // 1. Get recent changes via shared service
        let gitDiff = '';
        let changedFiles: string[] = [];

        try {
            const context = await this.analysisService.analyze({
                baseBranch,
                projectRoot: this.projectRoot,
                fallbackToLastCommit: true,
                includeSymbols: false, // We don't need semantic symbol analysis for this, just diffs + files
                stagedOnly: false,
            });

            gitDiff = context.gitDiff;
            changedFiles = context.changedFiles;

            if (!gitDiff) {
                this.logger.debug('No code changes detected to analyze.');
                return { hasDrift: false };
            }

            // FILTER: Remove README.md changes from the diff to prevent self-triggering
            // Using shared utility for consistent logic
            gitDiff = filterGitDiff(gitDiff, ['README.md', basename(readmePath)]);

            if (!gitDiff.trim()) {
                this.logger.debug('No code changes detected (after filtering README changes).');
                return { hasDrift: false };
            }

            // Optimization: Deterministic Pre-filter
            // We pass the ALREADY FILTERED diff here, so keywords in README.md don't trigger the AI check.
            if (!this.shouldAnalyzeWithAI(changedFiles, gitDiff)) {
                return { hasDrift: false };
            }

            // Truncate to avoid token limits
            if (gitDiff.length > 8000) {
                gitDiff = gitDiff.substring(0, 8000) + '\n... (truncated)';
            }
        } catch (error) {
            this.logger.warn('Failed to get changes: ' + error);
            return { hasDrift: false };
        }

        // 2. Read README content
        const readmeContent = readFileSync(readmePath, 'utf-8');

        // 3. Consult AI
        try {
            this.logger.info('🤖 Asking AI if README needs updates based on recent changes...');
            const aiAgents: AIAgents = createAIAgentsFromEnv({ debug: this.logger.getVerbose() });
            const plannerAgent = aiAgents.planner;

            if (!(await plannerAgent.validateConnection())) {
                this.logger.warn('AI connection failed. Skipping smart check.');
                return { hasDrift: false };
            }

            const prompt = getSmartCheckReadmePrompt(readmeContent, gitDiff);

            const response = await plannerAgent.generateText(prompt, {
                temperature: 0,
            });

            // Parse JSON response
            let result;
            try {
                // Strip markdown code blocks if present
                const cleanJson = response
                    .replace(/^```json\s*/, '')
                    .replace(/```$/, '')
                    .trim();
                result = JSON.parse(cleanJson);
            } catch (e) {
                this.logger.debug('Failed to parse AI response as JSON: ' + response);
                return { hasDrift: false };
            }

            if (result && result.hasDrift) {
                return {
                    hasDrift: true,
                    reason: result.reason,
                    suggestion: result.suggestion,
                };
            }
        } catch (error) {
            this.logger.warn('Smart check failed: ' + error);
        }

        return { hasDrift: false };
    }
}
