/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum SymbolType {
  Function = 'function',
  Class = 'class',
  Interface = 'interface',
  TypeAlias = 'type',
  Enum = 'enum',
  Variable = 'variable',
  Const = 'const'
}
export interface CodeSignature {
  symbolName: string
  symbolType: SymbolType
  signatureText: string
  isExported: boolean
}
export declare class AstAnalyzer {
  constructor()
  analyzeCode(code: string): Array<CodeSignature>
}
